"""empty message

Revision ID: 168fde7cd833
Revises: d57da8b21b98
Create Date: 2022-09-02 18:10:02.024869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168fde7cd833'
down_revision = 'd57da8b21b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
