"""profile pic edit

Revision ID: 26616817c89e
Revises: 4a6fe43f9a28
Create Date: 2022-09-02 17:53:31.582687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26616817c89e'
down_revision = '4a6fe43f9a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
