"""Add blog page

Revision ID: 274eee06b13f
Revises: 6e3d0c19500a
Create Date: 2022-08-30 11:26:52.306458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274eee06b13f'
down_revision = '6e3d0c19500a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=155), nullable=True),
    sa.Column('author', sa.String(length=155), nullable=True),
    sa.Column('slug', sa.String(length=155), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
